# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategorybrand',
            name='desc',
            field=models.TextField(default='', max_length=200, verbose_name='\u54c1\u724c\u63cf\u8ff0'),
        ),
    ]
