# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 03:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, '\u7559\u8a00'), (2, '\u6295\u8bc9'), (3, '\u8baf\u95ee'), (4, '\u552e\u540e'), (5, '\u6c42\u8d2d')], default=1, help_text='\u7559\u8a00\u7c7b\u578b:1(\u7559\u8a00),2(\u6295\u8bc9),3(\u8baf\u95ee),4(\u552e\u540e),5(\u6c42\u8d2d)', verbose_name='\u7559\u8a00\u7c7b\u578b')),
                ('message', models.TextField(default='', help_text='\u7559\u8a00\u5185\u5bb9', verbose_name='\u7559\u8a00\u5185\u5bb9')),
                ('file', models.FileField(help_text='\u4e0a\u4f20\u7684\u6587\u4ef6', upload_to=b'', verbose_name='\u4e0a\u4f20\u7684\u6587\u4ef6')),
                ('subject', models.CharField(default='', max_length=100, verbose_name='\u4e3b\u9898')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7559\u8a00',
                'verbose_name_plural': '\u7528\u6237\u7559\u8a00',
            },
        ),
        migrations.CreateModel(
            name='UsrAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(default='', max_length=100, verbose_name='\u533a\u57df')),
                ('address', models.CharField(default='', max_length=100, verbose_name='\u7528\u6237\u5730\u5740')),
                ('signer_name', models.CharField(default='', max_length=30, verbose_name='\u7b7e\u6536\u4eba')),
                ('signer_mobile', models.CharField(default='', max_length=11, verbose_name='\u7b7e\u6536\u624b\u673a')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5730\u5740',
                'verbose_name_plural': '\u7528\u6237\u5730\u5740',
            },
        ),
    ]
